return {
  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "catppuccin",
    },
  },
  {
    "catppuccin/nvim",
    name = "catppuccin",
    priority = 1000,
    opts = {
      flavour = "mocha",
      color_overrides = {
        mocha = {
          base = "{{ bg0 }}",
          mantle = "{{ bg1 }}",
          crust = "{{ bg0 }}",
          surface0 = "{{ bg2 }}",
          surface1 = "{{ bg3 }}",
          surface2 = "{{ bg3 }}",
          overlay0 = "{{ fg1 }}",
          overlay1 = "{{ fg1 }}",
          overlay2 = "{{ fg0 }}",
          text = "{{ fg0 }}",
          subtext0 = "{{ fg1 }}",
          subtext1 = "{{ fg0 }}",
          rosewater = "{{ red }}",
          flamingo = "{{ red }}",
          pink = "{{ magenta }}",
          mauve = "{{ magenta }}",
          red = "{{ red }}",
          maroon = "{{ bright_red }}",
          peach = "{{ yellow }}",
          yellow = "{{ yellow }}",
          green = "{{ green }}",
          teal = "{{ cyan }}",
          sky = "{{ bright_blue }}",
          sapphire = "{{ cyan }}",
          blue = "{{ blue }}",
          lavender = "{{ bright_magenta }}",
        },
      },
      custom_highlights = function(colors)
        return {
          CursorLine = { bg = "{{ bg2 }}" },
          Visual = { bg = "{{ bg3 }}" },
          Search = { bg = "{{ accent }}", fg = "{{ bg0 }}" },
          IncSearch = { bg = "{{ accent }}", fg = "{{ bg0 }}" },
          WinSeparator = { fg = "{{ bg3 }}" },
          VertSplit = { fg = "{{ bg3 }}" },
          CursorLineNr = { fg = "{{ accent }}" },
          LineNr = { fg = "{{ fg1 }}" },
          StatusLine = { bg = "{{ bg1 }}", fg = "{{ fg0 }}" },
          StatusLineNC = { bg = "{{ bg1 }}", fg = "{{ fg1 }}" },
          TabLine = { bg = "{{ bg1 }}", fg = "{{ fg1 }}" },
          TabLineFill = { bg = "{{ bg1 }}" },
          TabLineSel = { bg = "{{ bg2 }}", fg = "{{ fg0 }}" },
          NotifyBackground = { bg = "{{ bg1 }}" },
          GitSignsAdd = { fg = "{{ green }}" },
          GitSignsChange = { fg = "{{ yellow }}" },
          GitSignsDelete = { fg = "{{ red }}" },
          DiagnosticError = { fg = "{{ red }}" },
          DiagnosticWarn = { fg = "{{ yellow }}" },
          DiagnosticInfo = { fg = "{{ blue }}" },
          DiagnosticHint = { fg = "{{ cyan }}" },
          NormalFloat = { bg = "{{ bg1 }}" },
          FloatBorder = { fg = "{{ bg3 }}", bg = "{{ bg1 }}" },
          TelescopeNormal = { bg = "{{ bg1 }}" },
          TelescopeBorder = { fg = "{{ bg3 }}", bg = "{{ bg1 }}" },
          TelescopePromptBorder = { fg = "{{ bg3 }}", bg = "{{ bg1 }}" },
          TelescopeResultsBorder = { fg = "{{ bg3 }}", bg = "{{ bg1 }}" },
          TelescopePreviewBorder = { fg = "{{ bg3 }}", bg = "{{ bg1 }}" },
          Pmenu = { bg = "{{ bg1 }}" },
          PmenuSel = { bg = "{{ bg3 }}", fg = "{{ fg0 }}" },
          PmenuSbar = { bg = "{{ bg2 }}" },
          PmenuThumb = { bg = "{{ accent }}" },
          TreesitterContext = { bg = "{{ bg1 }}" },
          TreesitterContextLineNumber = { fg = "{{ accent }}" },
          WhichKey = { bg = "{{ bg1 }}" },
          WhichKeyFloat = { bg = "{{ bg1 }}" },
          NeoTreeNormal = { bg = "{{ bg1 }}" },
          NeoTreeNormalNC = { bg = "{{ bg1 }}" },
          NeoTreeFloatBorder = { fg = "{{ bg3 }}", bg = "{{ bg1 }}" },
          IblScope = { fg = "{{ accent }}" },
          IblIndent = { fg = "{{ bg2 }}" },
          MatchParen = { bg = "{{ accent }}", fg = "{{ bg0 }}" },
          Title = { fg = "{{ accent }}" },
          Special = { fg = "{{ accent }}" },
          SpecialKey = { fg = "{{ accent }}" },
          Question = { fg = "{{ accent }}" },
          MoreMsg = { fg = "{{ accent }}" },
          Directory = { fg = "{{ accent }}" },
          WildMenu = { bg = "{{ accent }}", fg = "{{ bg0 }}" },
          LspReferenceText = { bg = "{{ bg2 }}" },
          LspReferenceRead = { bg = "{{ bg2 }}" },
          LspReferenceWrite = { bg = "{{ bg2 }}" },
        }
      end,
    },
  },
}
