#!/usr/bin/env bash
# Create custom papirus icon theme with accent-colored folders
# Generated by dotman — minimal override theme, inherits from Papirus-Dark

set -e

THEME_NAME="dotman"
ACCENT="{{ accent }}"
SRC="/usr/share/icons/Papirus-Dark"
DST="$HOME/.local/share/icons/dotman-papirus"

rm -rf "$DST"
mkdir -p "$DST"

# Create index.theme — inherits all icons from Papirus-Dark
cat > "$DST/index.theme" << EOF
[Icon Theme]
Name=dotman-papirus
Comment=dotman Papirus icon theme with accent-colored folders
Inherits=Papirus-Dark
EOF

# Find all SVGs in Papirus-Dark that use ColorScheme-Text and replace with accent
find "$SRC" -name "*.svg" | while read -r src_svg; do
    # Check if this SVG uses ColorScheme-Text
    if grep -q "ColorScheme-Text" "$src_svg"; then
        # Get relative path
        rel="${src_svg#$SRC/}"
        dst_svg="$DST/$rel"
        mkdir -p "$(dirname "$dst_svg")"
        # Copy and replace the accent color
        sed "s/\.ColorScheme-Text { color:#[0-9a-fA-F]*/.ColorScheme-Text { color:${ACCENT}/g" "$src_svg" > "$dst_svg"
    fi
done

# Update icon caches
for dir in "$DST"/*/; do
    [ -d "$dir" ] && gtk-update-icon-cache -f -t "$dir" 2>/dev/null || true
done
