# Generated by Dotman
# Main Shell Config for Bash

# History
HISTFILE=~/.bash_history
HISTSIZE=10000
SAVEHIST=10000
shopt -s histappend
shopt -s checkwinsize
shopt -s globstar

# Completion
bind 'set show-all-if-ambiguous on'
bind 'set menu-complete-display-prefix on'

# Environment
export EDITOR=nvim
export VISUAL=nvim
export PAGER=less
export LESS="-R"
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export CARGO_HOME="$HOME/.local/share/cargo"
export RUSTUP_HOME="$HOME/.local/share/rustup"
export GOPATH="$HOME/.local/share/go"
export NPM_CONFIG_PREFIX="$HOME/.local/share/npm"
export PYTHONSTARTUP=~/.config/python/startup.py
export LESS_TERMCAP_mb=$'\e[1;31m'
export LESS_TERMCAP_md=$'\e[1;36m'
export LESS_TERMCAP_me=$'\e[0m'
export LESS_TERMCAP_se=$'\e[0m'
export LESS_TERMCAP_so=$'\e[1;44;33m'
export LESS_TERMCAP_ue=$'\e[0m'
export LESS_TERMCAP_us=$'\e[1;32m'

# PATH
export PATH="$HOME/.local/bin:$HOME/.local/share/cargo/bin:$HOME/.local/share/npm/bin:$HOME/.local/share/go/bin:/usr/local/bin:$PATH"

# Aliases
alias g='git'
alias gs='git status'
alias ga='git add'
alias gc='git commit'
alias gp='git push'
alias gl='git log --oneline -10'
alias gd='git diff'
alias gco='git checkout'
alias gb='git branch'
alias gst='git stash'
alias gsp='git stash pop'

alias ls='eza -la --icons --group-directories-first'
alias ll='eza -la --icons --group-directories-first'
alias la='eza -laa --icons --group-directories-first'
alias lt='eza --tree --level=2 --icons --group-directories-first'
alias tree='eza --tree --level=2 --icons --group-directories-first'

alias cat='bat'
alias find='fd'
alias top='btop'
alias ff='fastfetch'

alias v='vim'
alias vi='nvim'
alias vim='nvim'

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias ~='cd ~'

alias mk='mkdir -p'
alias rmrf='rm -rf'

alias py='python'
alias pip='pip'

alias k='kubectl'
alias d='docker'
alias dc='docker-compose'
alias dm='docker-compose'

alias tf='terraform'
alias tfl='terraform'

alias shl='start-hyprland'

# Functions
mkcd() {
    mkdir -p "$1" && cd "$1"
}

backup() {
    cp -r "$1" "$1".bak-$(date +%Y%m%d%H%M%S)
}

extract() {
    if [[ $# -ne 1 ]]; then
        echo "Usage: extract <file>"
        return 1
    fi
    
    case "$1" in
        *.tar.bz2) tar xjf "$1" ;;
        *.tar.gz) tar xzf "$1" ;;
        *.bz2) bunzip2 "$1" ;;
        *.rar) unrar x "$1" ;;
        *.gz) gunzip "$1" ;;
        *.tar) tar xf "$1" ;;
        *.tbz2) tar xjf "$1" ;;
        *.tgz) tar xzf "$1" ;;
        *.zip) unzip "$1" ;;
        *.Z) uncompress "$1" ;;
        *.7z) 7z x "$1" ;;
        *) echo "Cannot extract: $1" ;;
    esac
}

# Starship prompt
if command -v starship &> /dev/null; then
    eval "$(starship init bash)"
fi

# Colored man pages
export MANPAGER="less -R"

# Set default umask
umask 022

# Vi mode
set -o vi

# Direnv hook
if command -v direnv &> /dev/null; then
    eval "$(direnv hook bash)"
fi

# zoxide integration
if command -v zoxide &> /dev/null; then
    eval "$(zoxide init bash)"
fi

# FZF integration
if command -v fzf &> /dev/null; then
    export FZF_DEFAULT_COMMAND='fd --type f --hidden --follow --exclude .git'
    export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
    export FZF_ALT_C_COMMAND='fd --type d --hidden --follow --exclude .git'
fi

# Load completion for kubectl if installed
if command -v kubectl &> /dev/null; then
    source <(kubectl completion bash)
fi

# Load completion for docker if installed
if command -v docker &> /dev/null; then
    source /usr/share/bash-completion/completions/docker
fi

# Optional: Load bash-completion
if ! shopt -oq posix; then
    if [ -f /usr/share/bash-completion/bash_completion ]; then
        . /usr/share/bash-completion/bash_completion
    elif [ -f /etc/bash_completion ]; then
        . /etc/bash_completion
    fi
fi

# Optional: Load nvm (if installed)
# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Fastfetch on start
if command -v fastfetch &> /dev/null; then
    fastfetch
fi
