# Generated by Dotman
# Main Shell Config for Fish

# Environment
set -x EDITOR nvim
set -x VISUAL nvim
set -x PAGER less
set -x LESS -R
set -x XDG_CONFIG_HOME $HOME/.config
set -x XDG_DATA_HOME $HOME/.local/share
set -x XDG_STATE_HOME $HOME/.local/state
set -x CARGO_HOME $HOME/.local/share/cargo
set -x RUSTUP_HOME $HOME/.local/share/rustup
set -x GOPATH $HOME/.local/share/go
set -x NPM_CONFIG_PREFIX $HOME/.local/share/npm
set -x PYTHONSTARTUP ~/.config/python/startup.py
set -x HISTSIZE 10000
set -x SAVEHIST 10000
set -x LESS_TERMCAP_mb (printf "\033[1;31m")
set -x LESS_TERMCAP_md (printf "\033[1;36m")
set -x LESS_TERMCAP_me (printf "\033[0m")
set -x LESS_TERMCAP_se (printf "\033[0m")
set -x LESS_TERMCAP_so (printf "\033[1;44;33m")
set -x LESS_TERMCAP_ue (printf "\033[0m")
set -x LESS_TERMCAP_us (printf "\033[1;32m")

# PATH
fish_add_path $HOME/.local/bin
fish_add_path $HOME/.local/share/cargo/bin
fish_add_path $HOME/.local/share/npm/bin
fish_add_path $HOME/.local/share/go/bin
fish_add_path /usr/local/bin

# Abbreviations (like aliases but expanded)
abbr -a g git
abbr -a gs git status
abbr -a ga git add
abbr -a gc git commit
abbr -a gp git push
abbr -a gl git log --oneline -10
abbr -a gd git diff
abbr -a gco git checkout
abbr -a gb git branch
abbr -a gst git stash
abbr -a gsp git stash pop

abbr -a ls eza -la --icons --group-directories-first
abbr -a ll eza -la --icons --group-directories-first
abbr -a la eza -laa --icons --group-directories-first
abbr -a lt eza --tree --level=2 --icons --group-directories-first
abbr -a tree eza --tree --level=2 --icons --group-directories-first

abbr -a cat bat
abbr -a find fd
abbr -a top btop
abbr -a ff fastfetch

abbr -a v vim
abbr -a vi nvim
abbr -a vim nvim

abbr -a .. cd ..
abbr -a ... cd ../..
abbr -a .... cd ../../..
abbr -a ~ cd ~

abbr -a mk mkdir -p
abbr -a rmrf rm -rf

abbr -a py python
abbr -a pip pip

abbr -a k kubectl
abbr -a d docker
abbr -a dc docker-compose
abbr -a dm docker-compose

abbr -a tf terraform
abbr -a tfl terraform

abbr -a shl start-hyprland

# Functions
function fish_greeting
    if type -q fastfetch
        fastfetch
    end
end

function mkcd
    mkdir -p $argv[1]; and cd $argv[1]
end

function backup
    cp -r $argv[1] $argv[1].bak-(date +%Y%m%d%H%M%S)
end

function extract
    if test (count $argv) -ne 1
        echo "Usage: extract <file>"
        return 1
    end
    
    switch $argv[1]
        case '*.tar.bz2'
            tar xjf $argv[1]
        case '*.tar.gz'
            tar xzf $argv[1]
        case '*.bz2'
            bunzip2 $argv[1]
        case '*.rar'
            unrar x $argv[1]
        case '*.gz'
            gunzip $argv[1]
        case '*.tar'
            tar xf $argv[1]
        case '*.tbz2'
            tar xjf $argv[1]
        case '*.tgz'
            tar xzf $argv[1]
        case '*.zip'
            unzip $argv[1]
        case '*.Z'
            uncompress $argv[1]
        case '*.7z'
            7z x $argv[1]
        case '*'
            echo "Cannot extract: $argv[1]"
    end
end

# Starship prompt
if type -q starship
    starship init fish | source
end

# Fisher (plugin manager)
if not functions -q fisher
    set -q XDG_CONFIG_HOME; or set XDG_CONFIG_HOME ~/.config
    if test -f "$XDG_CONFIG_HOME/fish/plugins.fish"
        source "$XDG_CONFIG_HOME/fish/plugins.fish"
    end
end

# Colored man pages
set -gx MANPAGER "less -R"

# Set default umask
umask 022

# Enable vi mode
fish_vi_key_bindings

# Load completion for supported tools
# These are typically auto-loaded, but we ensure they're available
set -g __fish_use_subcommands foo

# Key bindings
if type -q direnv
    direnv hook fish | source
end

# zoxide integration
if type -q zoxide
    zoxide init fish | source
end

# FZF integration
if type -q fzf
    set -gx FZF_DEFAULT_COMMAND 'fd --type f --hidden --follow --exclude .git'
    set -gx FZF_CTRL_T_COMMAND "$FZF_DEFAULT_COMMAND"
    set -gx FZF_ALT_C_COMMAND 'fd --type d --hidden --follow --exclude .git'
end
