#!/usr/bin/env bash
# Setup custom GTK theme - generated by dotman
# Copies adw-gtk3-dark as base, dotman then applies CSS overrides

set -e

THEME_DIR="$HOME/.local/share/themes/dotman-gtk-dark"
SRC="/usr/share/themes/adw-gtk3-dark"

# Copy base theme if not already present
if [ ! -d "$THEME_DIR" ]; then
    cp -r "$SRC"/* "$THEME_DIR/"
    echo "GTK theme base copied to: $THEME_DIR"
else
    echo "GTK theme already exists: $THEME_DIR"
fi

# Ensure CSS file is in place
mkdir -p "$THEME_DIR/gtk-3.0"
mkdir -p "$THEME_DIR/gtk-4.0"
