# System Services
exec-once = systemctl --user start hyprpolkitagent
exec-once = hypridle

# Clipboard
exec-once = wl-paste --watch cliphist store

# Notifications
exec-once = mako

# Wallpaper & Bar
exec-once = hyprpaper
exec-once = ~/.config/wallpapers/set-wallpaper.sh
exec-once = waybar

# Force the cursor on launch
exec-once = hyprctl setcursor phinger-cursors-dark 24

# GTK Theme
exec-once = gsettings set org.gnome.desktop.interface gtk-theme "adw-gtk3-dark"
exec-once = gsettings set org.gnome.desktop.interface icon-theme "dotman-papirus"
exec-once = gsettings set org.gnome.desktop.interface font-antialiasing 'rgba'
exec-once = gsettings set org.gnome.desktop.interface font-hinting 'slight'

# Ensure the portal environment is updated for Waybar to see these settings
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
